### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Arno-Enslin**
Changes because of new No Flex option in Autohint.py

### CODE REVIEW

**Comment by miguelsousa** [comment]
where did this `plistlib.py` script come from and why is it needed?

**Comment by Arno-Enslin** [comment]
Hi Miguel,

> where did this plistlib.py script come from […] ?

It comes from [adobe-type-tools/afdko/tree/master/FDK/Tools/SharedData/FDKScripts](https://github.com/adobe-type-tools/afdko/tree/master/FDK/Tools/SharedData/FDKScripts).

> […] and why is it needed?

Because of this line in the macro "Autohint.py":

But I just have seen, that it was never contained in the modules directory of FDK/Tools/Fontlab(Macros). Older versions of "installFontLabMacros.py" got it from "…/Tools/SharedData/FDKScripts".

But because you have sourced out the FontLab directory from the AFDKO, I don't know, if "installFontLabMacros.py" should be changed again.

[Please have a look at this issue discussion / monologue](https://github.com/adobe-type-tools/afdko/issues/143) [;‑)].

And please let me know, if you know, how I can access the FontLab checkbox "Automatically generate Flex hints in T1 and OT-PS fonts", because I would like to add an option to Autohint.py for turning this on/off.

**Comment by miguelsousa** [comment]
OK.
> let me know, if you know, how I can access the FontLab checkbox "Automatically generate Flex hints in T1 and OT-PS fonts"

I don't.

**Comment by frankrolf** [comment]
`plistlib.py` is a built-in Python module and hence should not be in this repository.
https://docs.python.org/2/library/plistlib.html

**Comment by Arno-Enslin** [comment]
@ Frank

Plistlib.py is not contained in the lib of Python 2.4. But FontLab Studio 5.04 needs Python 2.3 or 2.4 for the macros as far as I know.

And Plistlib.py was copied to the FontLab directory "Macros/System/Modules" by older versions of "installFontLabMacros.py".

If Plistlib.py is not in the modules directory, FontLab posts an error message, if you start the macro Autohint.py. By the way: The name of the macro is almost identical with the name of the command line version (autohint.py). I would rename Autohint.py to Autohint_Macro.py.

**Comment by frankrolf** [comment]
The “current” version of FLS on Windows is 5.2, which uses Python 2.7.

**Comment by Arno-Enslin** [comment]
I know. But I don't use FLS 5.2. Too many bugs. FLS 5.04 is relatively stable on Windows.

**Pull request merged**
